### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Element21** [ThatFruedDued/JustSomeRandomFiles#2]
just get alert('waiting for answer load') and nothing else. Maybe if you didn't obfuscate so much I could see the problem.

**Comment by ThatFruedDued** [comment]
Sorry for the late reply. You must activate the hack when joining the game. If you are already doing this, I can look into the issue.

**Comment by ThatFruedDued** [comment]
The hack seems to still be working for me. Make sure you run the Javascript before you join the game. Then, once you join, you should see alert('Answers successfully loaded'). Then, just press the 'w' key to answer correctly. If the issue persists, please reply to this issue with the steps to reproduce your error. 

Why some of my code is obfuscated:
Because of the nature of some scripts, the code may be hard to read or obfuscated. This is to protect the code. This is helpful for a number of reasons, including, but not limited to preventing others from modifying the code in a way that hides my contribution to the project. Also, obfuscation could help if my code uses a loophole that could be patched more easily if non-obfuscated code was published.

**Comment by ThatFruedDued** [comment]
You have not responded for five days. Because of this, I am assuming the issue is solved and you do not need my help anymore. Please feel free to reopen this issue if necessary.
